// <auto-generated />
namespace Estoque.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UpProdutos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpProdutos));
        
        string IMigrationMetadata.Id
        {
            get { return "201807112159025_UpProdutos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
